name: artifact

on: [push]

env:
  ARTIFACT_NAME: challenge2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: ${{ env.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.ARTIFACT_NAME }}
