name: challenge1

on: push

jobs:
  ubuntu:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date
  windows:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date

  macos:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date

  depands:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo 'I am job 4'
