name: challenge2

on: [push]

env:
  ARTIFACT_NAME: challenge2Env

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build ${{ env.ARTIFACT_NAME }} for ubuntu-latest
        run: go build ${{ env.ARTIFACT_NAME }}.go

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
