name: challenge1

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo "NOW=Get-Date -format "yyyy-MM-dd"" >> $env:GITHUB_ENV

  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo date -j -vJulm -v20d -v1999y '+%A'

  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo 'I am job 4'
